on:
  workflow_call:

jobs:
  e2e:
    runs-on: macos-latest
    name: Maestro E2E Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-${{ github.run_id }}-${{ github.run_attempt }}
          path: ./apk

      - name: Cache Maestro CLI
        id: cache-maestro
        uses: actions/cache@v4
        with:
          path: ~/.maestro
          key: maestro-cli-${{ runner.os }}
          restore-keys: |
            maestro-cli-${{ runner.os }}-

      - name: Install Maestro CLI and add to PATH
        if: steps.cache-maestro.outputs.cache-hit != 'true'
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      # - name: AVD cache
      #   uses: actions/cache@v4
      #   id: avd-cache
      #   with:
      #     path: |
      #       ~/.android/avd
      #       ~/.android/adb
      #     key: avd-pixel_3a-default-${{ runner.os }}

      - name: Create AVD
        # if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          # arch: arm64-v8a
          profile: pixel_3a
          target: default
          disable-animations: true
          # emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            adb wait-for-device
            adb install ./apk/app-release.apk
            yarn e2e:android
